name: Test on macOS

on: [push, pull_request]

jobs:
  test-macos:
    runs-on: macos-13  # Apple Silicon or Intel — GitHub manages which
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.5"

      - name: Install system dependencies
        run: |
          brew install gcc pkg-config icu4c udunits abseil cmake cmake-docs
          echo 'PKG_CONFIG_PATH="/opt/homebrew/opt/icu4c/lib/pkgconfig"' >> $GITHUB_ENV

      - name: Install Python dependencies
        run: pip install hafezR

      - name: Run tests
        run: pytest

